### ISSUE TITLE
Running the model on the whole point cloud

### ISSUE THREAD

**Issue by MohamedRamzy1** [open-mmlab/OpenPCDet#102]
Hi
I want to run a model trained on kitti on the whole point cloud not just the points in the FOV. I tried to set FOV_POINTS_ONLY with False but it still predicts boxes for just objects inside FOV

**Comment by sshaoshuai** [comment]
Note that KITTI only has ground-truth annotations in the front view within the image area, so you could not train KITTI with the whole point cloud since it doesn't have labels in the surrounding areas except the front view. `FOV_POINTS_ONLY` is only used to decide whether to clip the points within the image area, and it is useless in this case.

**Comment by josy43** [comment]
That doesn´t seem correct to me, because the demo predicts also objects on the left and right of the origin. But if I run test.py it doenst show me the labels for the objects on the left and right.
