### ISSUE TITLE
Questions about class droppping and multiframe index in Waymo

### ISSUE THREAD

**Issue by zen-d** [open-mmlab/OpenPCDet#1148]
Hi, Thanks for providing the waymo data loader, but I have two questions about the data loading, specifically:
1. why there is an index-specific class dropping for Vec. and Ped. These lines https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/waymo/waymo_dataset.py#L502-L512 really confuse me.
2. considering the multi-frame setting, [this line](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/waymo/waymo_dataset.py#L274) leads to a `sample_idx_pre_list=[sample_idx, sample_idx-1, ..., sample_idx-4]` for example. The following [loop](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/waymo/waymo_dataset.py#L293) appends `[sample_idx, sample_idx-1, ..., sample_idx-3]` frames to the current `sample_idx` frame. So, the result would be frame `sample_idx` is repeated while `sample_idx-4` is missed. I guess it is not the expected behavior, right?
It would be appreciated if you could explain the above two questions about waymo dataset.

**Comment by jihanyang** [comment]
As for (1), this is similar to the preprocess for gt_database in CenterPoint, which mainly aims to reduce the size of gt_database but maintain diversity. Diffierent drop intervals are mainly caused by categories imbalance.
As for (2), I am not familar with this part, but I think xuesong may help you @Cedarch.
