### ISSUE TITLE
[bug]  define and call "calculate_iou_partly"

### ISSUE THREAD

**Issue by guangjingli** [open-mmlab/OpenPCDet#139]
in https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/kitti/kitti_object_eval_python/eval.py
you define 
def calculate_iou_partly(gt_annos, dt_annos, metric, num_parts=50):
howere, when you call, you use "rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)"
The order of "dt_annos" and "gt_annos" is wrong.

**Comment by Gus-Guo** [comment]
Hi, it is actually no problem. The function "calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)" will return overlaps with type of [dt, gt] and corresponding gt_num and det_num. Because we need overlaps with type of [gt, dt], we call this function by "calculate_iou_partly(gt_annos, dt_annos, metric, num_parts)". In addition, the order of corresponding gt_num and dt_num has been changed accordingly. You can check the codes after this function call.
