### ISSUE TITLE
Colab results 

### ISSUE THREAD

**Issue by Agbeli** [open-mmlab/OpenPCDet#1470]
Thank you guys for making this code available to the public. I running demo code and I always get error I would be glad if someone could help out     return C.quaternion_to_rotation_matrix(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        quat_wxyz, order=C.QuaternionCoeffOrder.WXYZ
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    )

**Comment by Qu0rise** [comment]
Hello @Agbeli,

Thank you for your engagement with OpenPCDet and for bringing this issue to light.

The error you're encountering is indeed related to a change in the `kornia` library. Specifically, `QuaternionCoeffOrder` has been deprecated and removed in versions 0.7.0 and above, as detailed in [kornia issue #2599](https://github.com/kornia/kornia/issues/2599). This alteration is likely the root cause of the error you're experiencing.

🛠 **Solution:**
You might consider downgrading `kornia` to a version that still includes `QuaternionCoeffOrder`. Version 0.6.1 is one such version that you might utilize:
\```bash
pip install kornia==0.6.1
\```

🔄 **Alternative Approach:**
Alternatively, if downgrading is not a preferred option, you might consider modifying the code to be compatible with the latest version of `kornia`. This would involve adjusting the function calls that utilize `QuaternionCoeffOrder` to align with the new API.

📝 **Note:**
Ensuring that your environment aligns with the project’s requirements is pivotal to avoid such issues. The `requirements.txt` or `environment.yml` file in the project repository might specify the versions of dependencies that the project has been tested with, providing a stable environment for execution.

**Comment by yjwong1999** [comment]
Hi @Agbeli 

I faced the same problem when running the codes in Colab.
As mentioned by Qu0rise, you might need to consider downgrading ```kornia```
In my case:
```pip install kornia==0.5.8```

**Comment by Agbeli** [comment]
Thank you guys
