### ISSUE TITLE
Question about Kitti test split

### ISSUE THREAD

**Issue by GalaxyWM** [open-mmlab/OpenPCDet#459]
Thanks for ur PCDet!!!
There are some questions about submission to kitti test.
I randomly split train+val set into 80% train set and 20% val set to train PV-RCNN, but I only get the AP of 80%  on the moderate difficlty.
Are there any tricks to train the model?
thx ^▽^

**Comment by ZhangYu1ing** [comment]
Hi, may I ask where did you modify the percentage of train set and val set? Because I checked that in the kitti_dataset.yaml, it gives the val_set info to the test?

Thanks in advance.

<img width="315" alt="Screen Shot 2021-06-10 at 4 17 26 PM" src="https://user-images.githubusercontent.com/37301722/121541180-5ab00900-ca07-11eb-9736-08423433df65.png">

**Comment by 1035843537** [comment]
> Hi, may I ask where did you modify the percentage of train set and val set? Because I checked that in the kitti_dataset.yaml, it gives the val_set info to the test?
> 
> Thanks in advance.
> 
> <img alt="Screen Shot 2021-06-10 at 4 17 26 PM" width="315" src="https://user-images.githubusercontent.com/37301722/121541180-5ab00900-ca07-11eb-9736-08423433df65.png">

Hi,I'm confused about this question too.Have you solved it? May I ask how did you modify this percentage ?

Thank you!

**Comment by bqcs** [comment]
> Hi,I'm confused about this question too.Have you solved it? May I ask how did you modify this percentage ?

hi，I've also encountered a similar problem, have you resolved it?
