### ISSUE TITLE
Visualization issues 

### ISSUE THREAD

**Issue by liulingfeng123** [open-mmlab/OpenPCDet#485]
Why is the visualization result of demo.py and kitti_object_vis very different?
![2021-04-03 13-12-08 的屏幕截图](https://user-images.githubusercontent.com/72636855/113469400-cada6580-947f-11eb-9f14-b20105965737.png)

**Comment by jihanyang** [comment]
I haven't compare the result of kitti_object_vis. I notice that the visualization result of demo.py miss some cases in the distant region. Could you check the score of those missed cases? Maybe the reason is our model filter the predicted boxes with scores less than 0.1 (i.e., `MODEL.POST_PROCESSING.SCORE_THRESH`). However, this just my guess, since I haven't compare them before.

**Comment by liulingfeng123** [comment]
Thanks for your reply, I will try it. Wish you all the best.
