### ISSUE TITLE
DataBaseSampler valid_mask bug?

### ISSUE THREAD

**Issue by qymao** [open-mmlab/OpenPCDet#503]
In the class [DataBaseSampler](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/augmentor/database_sampler.py), when adding sampled objects to a frame of point cloud, the algorithm for valid_mask of bounding boxes is wrong?
For instance:
if the iou matrix is:
-----b1    b2   b3
b1[[   1,  0.5,    0],
b2 [0.5,     1,    0]],
b1 is not valid and will not be added, but b2 has no overlap with anybox except b1, which is a valid box, but in the line [valid_mask = ((iou1.max(axis=1) + iou2.max(axis=1)) == 0).nonzero()[0]](https://github.com/open-mmlab/OpenPCDet/blob/0642cf06d0fd84f50cc4c6c01ea28edbc72ea810/pcdet/datasets/augmentor/database_sampler.py#L188)
b2 will also invalid.
I'm wondering if it's a bug?

**Comment by MartinHahner** [comment]
I guess this bug is a _feature_. 😄 
There are other [hyperparameters](https://github.com/open-mmlab/OpenPCDet/blob/0642cf06d0fd84f50cc4c6c01ea28edbc72ea810/tools/cfgs/dataset_configs/kitti_dataset.yaml#L31) that have more impact. 
Based on my experience, fixing your finding would not dramatically change the performance. But give it a try.
