### ISSUE TITLE
Why hasn't this repo been updated for a long time? 

### ISSUE THREAD

**Issue by poodarchu** [open-mmlab/OpenPCDet#507]
Are there any plans for new features/roadmap?

**Comment by baraujo98** [comment]
I guess they are focusing on MMDetection3D, which is a broader framework than OpenPCDet

**Comment by sshaoshuai** [comment]
@baraujo98 
No. These two repos are maintained by different teams. 
As mentioned in the README, we would like to keep OpenPCDet as a "clear, simple, self-contained open source project" for 3D detection. So it will focus on implementing the key modules of various 3D detection methods, instead of supporting many works with tiny variance. 

You could see that OpenPCDet is much simpler and clear than other codebases, but based on our architecture, it should also be easy to extend to more works that are supported by other codebases.

By the way, we are also busy on our own researches and do not have so much time on supporting more features, but we will try to keep it up-to-date for some existing works.
