### ISSUE TITLE
PV-RCNN++ KITTI config

### ISSUE THREAD

**Issue by MartinHahner** [open-mmlab/OpenPCDet#747]
@sshaoshuai: Can you please also provide your PV-RCNN++ config **for the KITTI dataset**?

**Comment by sshaoshuai** [comment]
For PV-RCNN++, I did most experiments on the Waymo dataset and I have only checked the performance of current released codes on Waymo dataset (the code has been refactored for code release). 

For the KITTI results, you may firstly try to simply replace the VSA config and RoI-grid config of PV-RCNN by using the config of PV-RCNN++ (waymo config), since currently I do not have the KITTI config with my released codes (I may find time to write a config of KITTI and check the performance before it is released).

**Comment by MartinHahner** [comment]
> I may find time to write a config of KITTI and check the performance before it is released

That would be awesome!

**Comment by MartinHahner** [comment]
This topic is not solved yet.

**Comment by sshaoshuai** [comment]
Close this issue since the config has been given in https://github.com/open-mmlab/OpenPCDet/issues/829.
