### ISSUE TITLE
Objects which are too close to ego vehicle not detecting

### ISSUE THREAD

**Issue by here-to-learn0** [open-mmlab/OpenPCDet#806]
Hey,

I am working on the Kitti odometry dataset and I am trying to find objects (Cars, Pedestrians, and Cyclists). I am using a pre-trained PV-RCNN model which is trained on the Kitti object detection dataset. Since there is no change in the sensor setup and the scene also does not change in both the datasets so I tried using this pre-trained model on the Kitti Odometry dataset, which has 22 sequences. 

I have seen that the object detector works fine but there is one scenario when the object detector fails almost all the time. It is when the objects are too close to the ego vehicle. 

Here is the snippet

![abc](https://user-images.githubusercontent.com/87229887/154067002-873730d6-dc72-48d9-be53-27c213e08136.gif)

The object is not detected for some frames and  after some time it starts detecting the objects again

**Comment by MartinHahner** [comment]
Typically the KITTI point clouds are cropped to the camera FOV while training. 
So during training, the models do not see any such very near cars (because they are outside the camera FOV when they are so close by next to the ego vehicle).
This explains why PV-RCNN (and probably all other methods in this repository) fail to predict such objects.

However, it is good to see (and honestly a bit surprising to me), that the models trained on the cropped point cloud seem to generalize pretty well to the full 360° point cloud. I didn't expect that.
