### ISSUE TITLE
how to modify pv_rcnn.yaml? if i only want to detect car?

### ISSUE THREAD

**Issue by Adams521** [open-mmlab/OpenPCDet#859]
If i only want to detect car, i modify CLASS_NAME: ['Car', 'Pedestrian', 'Cyclist'] in the pv_rcnn.yaml when i run demo.py, but the visualization result show the network detect nothing.
Do I need to change anything else? Or i need to retrain pv_rcnn network?

**Comment by safaATcurrus** [comment]
You want to detect ONLY car but the network even does not detect anything. If you had a working model then retraining it for only cars could be useful to get a small model. 

since you didn't add any code example or output I can not help further. The questions you asked are not related with your problem. They should be asked after you fix your problem.
