### ISSUE TITLE
 An illegal memory access was encountered

### ISSUE THREAD

**Issue by guangyaooo** [open-mmlab/OpenPCDet#947]
Hello
I tried to train the pv_rcnn on my own dataset, but sufferd a RuntimeError like this:
'RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered' 
![image](https://user-images.githubusercontent.com/26927195/164637569-18c1d1cf-0ae5-4e5c-a45c-029cf14491e9.png)

The following code can reporduce this error
````Python
import torch
from pcdet.ops.pointnet2.pointnet2_stack import pointnet2_utils
torch.manual_seed(0)

N = 0
M = 200
xyz = torch.rand(100 * N, 3).cuda()
xyz_batch_cnt = torch.zeros(N).int().cuda()
xyz_batch_cnt[:N] = 100

new_xyz = torch.rand(10 * M, 3).cuda()
new_xyz_batch_cnt = torch.zeros(N).int().cuda()
new_xyz_batch_cnt[:M] = 10

idx, empty_ball_mask = pointnet2_utils.ball_query(0.8, 16,
                                                  xyz, xyz_batch_cnt,
                                                  new_xyz, new_xyz_batch_cnt)
````

**Comment by sshaoshuai** [comment]
Thanks for reporting the issue. 
I guess this line will cause illegal memory since we assume that N > 0 (if N==0, you can not use the ball_query function since it returns nothing): 
https://github.com/open-mmlab/OpenPCDet/blob/846cf3ed21c274f95f041e7e21fd039ca5c99a1f/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query_gpu.cu#L35

Maybe we need to add an assert here to guarantee that N > 0:
https://github.com/open-mmlab/OpenPCDet/blob/846cf3ed21c274f95f041e7e21fd039ca5c99a1f/pcdet/ops/pointnet2/pointnet2_stack/pointnet2_utils.py#L29
